### ISSUE TITLE
See potential enemy moves/attacks

### ISSUE THREAD

**Issue by j0e1GMR** [nsmryan/RustTcodTutorial#4]
It would be cool to have a feature like Hoplite where you can see where enemies can attack next turn, and maybe where they are able to move as well.  This could be on mouseover, or just show with a slight visual change all the time.

**Comment by nsmryan** [comment]
This seems doable. There is already an Ai type, which I would think indicates monster movement. Otherwise we would add a movement type for this. Then we need a function from this type to a set of offsets, which are the offsets that the monster can move too.


Then on mouse over, if the object has the right properties, we could draw a different shade on the provided squares.

**Comment by nsmryan** [comment]
Pushed a branch with part of this change. Does not yet work completely, but close.

**Comment by nsmryan** [comment]
This is implemented in the branch feature_move_and_attack.

The positions the monster can move are shown in '.'s and the positions they can attack are in 'x's.

This all seems to work, so as soon as the branch is merged, we can close this issue.

**Comment by nsmryan** [comment]
I've merged this branch, so I'm closing the issue.
