### ISSUE TITLE
sound 

### ISSUE THREAD

**Issue by j0e1GMR** [nsmryan/RustTcodTutorial#6]
It would be cool if throwing a rock or moving, and especially running or doing parkour moves caused sound that alerted monsters (monsters... they look like monsters to you?)

**Comment by nsmryan** [comment]
I added the rodio crate and tested that we can play a sound file while playing the game. I haven't found a good effect, but it doesn't look to hard to play them when we find them.

**Comment by nsmryan** [comment]
I put this into a function to play a sound file, but its in my feature_mouseover_position branch right now.

**Comment by j0e1GMR** [comment]
We could highlight the areas where sound can be heard (around the stone strike for example), briefly after it hits, for now, to see if its interesting.

**Comment by nsmryan** [comment]
I pushed a commit that adds sound to the game.
The map tiles now contain a field indicating if a sound can be heard from that tile, and if so it contains the x/y position that created the sound.

The sound tiles get a '.' character drawn on them as a first cut at an animation for sound.

Enemies now have a limited visual range (currently 6 tiles) so that the player can see them an throw a stone within always being seen.

Enemies will seek to the stone, but will attack the player if they are in sight.

**Comment by nsmryan** [comment]
I think the way to use sound for the player's movement would be to create a sound radius around the player of some large area when they perform certain movements.
It seems like this would have to be fairly large to make a difference. Ideally the player would realize that this was happening and either would alert visible enemies, or make enemies track them from behind obstacles.

**Comment by nsmryan** [comment]
The develop branch has an implementation of sound with a visual indicator. Sounds can be heard through walls.
Stones make a sound, and enemies investigate those sounds.
